lets see what a dummy overall-result job does

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -18,7 +18,6 @@ on:
     branches:
       - main
   merge_group:
-
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
@@ -82,21 +81,18 @@ jobs:
               echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
               ./scripts/publish.sh --${{ matrix.os }} "main"
             fi
-
   overall-result:
     name: build/overall-result
-    description: Overall Result
     runs-on: ubuntu-24.04
-    needs: [build/amd64, build/arm64]
-    if: ${{ !cancelled() }}
+    # needs: [build/amd64, build/arm64]
+    # if: ${{ !cancelled() }}
     steps:
       - name: Successful verification
-        if: ${{ !(contains(needs.*.result, 'failure')) }}
+        # if: ${{ !(contains(needs.*.result, 'failure')) }}
         run: exit 0
-      - name: Failing verification
-        if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
-
+        # - name: Failing verification
+        #   if: ${{ contains(needs.*.result, 'failure') }}
+        #   run: exit 1
   merge:
     name: Merge Labels (main only)
     needs: [build]
